### ISSUE TITLE
Please open source the code

### ISSUE THREAD

**Issue by world1tree** [xuchennlp/S2T#1]

**Comment by xuchennlp** [comment]
We apologize for the delay in open sourcing our code. We wanted to include our implementation of our recent conference paper submission, which caused a longer preparation time.

We are actively working to finalize the training scripts to make reproduction smoother for everyone. Our plan is to release the code publicly within the next week.

Thank you for your patience and interest! We are excited to share our work soon.

Please let us know if you have any other questions in the meantime.

**Comment by xuchennlp** [comment]
Hi, the code has been uploaded, welcome to try it out.

**Comment by xuchennlp** [comment]
Hi, the code has been uploaded, welcome to try it out.
